include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/l10n/app_localizations.dart
    - lib/screens/firewall_rule_form_screen.dart
    - lib/screens/home_screen.dart
    - lib/screens/profile_form_screen.dart
    - lib/screens/system_info_screen.dart

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false
    prefer_single_quotes: true
