import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../l10n/app_localizations.dart';
import '../models/firewall_rule.dart';
import '../providers/session_provider.dart';

class FirewallRuleFormScreen extends StatefulWidget{const FirewallRuleFormScreen({super.key,this.rule});final FirewallRule? rule;@override State<FirewallRuleFormScreen> createState()=>_FirewallRuleFormScreenState();}
class _FirewallRuleFormScreenState extends State<FirewallRuleFormScreen>{final _key=GlobalKey<FormState>();late String _type=widget.rule?.type??'pass';late String _interface=widget.rule?.interface.isNotEmpty==true?widget.rule!.interface:'wan';late String _protocol=widget.rule?.protocol??'tcp';late final _src=TextEditingController(text:widget.rule?.sourceNetwork??'*');late final _dst=TextEditingController(text:widget.rule?.destinationNetwork??'*');late final _from=TextEditingController(text:widget.rule?.destinationPortFrom?.toString()??'');late final _to=TextEditingController(text:widget.rule?.destinationPortTo?.toString()??'');late final _desc=TextEditingController(text:widget.rule?.description??'');late bool _enabled=widget.rule?.enabled??true;bool _saving=false;@override void dispose(){_src.dispose();_dst.dispose();_from.dispose();_to.dispose();_desc.dispose();super.dispose();}Future<void> _save()async{if(!_key.currentState!.validate())return;final s=context.read<PfSenseSessionProvider>();final l=AppLocalizations.of(context);if(!s.connected||s.service==null){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(l?.disconnectedMessage??'Disconnected')));return;}setState(()=>_saving=true);final r=FirewallRule(id:widget.rule?.id,section:widget.rule?.section??'rules',type:_type,interface:_interface,protocol:_protocol,sourceType:'network',sourceNetwork:_src.text.trim(),destinationType:'network',destinationNetwork:_dst.text.trim(),destinationPortFrom:int.tryParse(_from.text.trim()),destinationPortTo:int.tryParse(_to.text.trim()),description:_desc.text.trim(),enabled:_enabled,createdTime:widget.rule?.createdTime??DateTime.now().toIso8601String());try{if(r.id==null||r.id!.isEmpty){await s.service!.createFirewallRule(r.toJson());}else{await s.service!.updateFirewallRule(r.id!,r.toJson());}if(mounted)Navigator.pop(context,true);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}finally{if(mounted)setState(()=>_saving=false);}}
@override Widget build(BuildContext context){final l=AppLocalizations.of(context);context.watch<PfSenseSessionProvider>();return Scaffold(appBar:AppBar(title:Text(widget.rule==null?(l?.addRule??'Add rule'):(l?.editRule??'Edit rule'))),body:Form(key:_key,child:ListView(padding:const EdgeInsets.all(16),children:[SegmentedButton<String>(selected:{_type},segments:[ButtonSegment(value:'pass',label:Text(l?.pass??'Pass')),ButtonSegment(value:'block',label:Text(l?.block??'Block')),ButtonSegment(value:'reject',label:Text(l?.reject??'Reject'))],onSelectionChanged:(v)=>setState(()=>_type=v.first)),SwitchListTile(value:_enabled,onChanged:(v)=>setState(()=>_enabled=v),title:Text(_enabled?(l?.enabled??'Enabled'):(l?.disabled??'Disabled'))),_drop(l?.interface??'Interface',_interface,['wan','lan','opt1','opt2'],(v)=>setState(()=>_interface=v)),const SizedBox(height:12),_drop(l?.protocol??'Protocol',_protocol,['any','tcp','udp','icmp','tcp/udp'],(v)=>setState(()=>_protocol=v)),const SizedBox(height:12),_field(_src,l?.source??'Source',validator:_req),_field(_dst,l?.destination??'Destination',validator:_req),Row(children:[Expanded(child:_field(_from,l?.portFrom??'Port from',number:true,validator:_port)),const SizedBox(width:12),Expanded(child:_field(_to,l?.portTo??'Port to',number:true,validator:_port))]),_field(_desc,l?.description??'Description',maxLines:3),const SizedBox(height:16),FilledButton.icon(onPressed:_saving?null:_save,icon:const Icon(Icons.save_outlined),label:Text(l?.save??'Save'))])));}Widget _drop(String label,String value,List<String> values,ValueChanged<String> onChanged)=>DropdownButtonFormField<String>(value:values.contains(value)?value:values.first,decoration:InputDecoration(labelText:label),items:[for(final i in values)DropdownMenuItem(value:i,child:Text(i.toUpperCase()))],onChanged:(v){if(v!=null)onChanged(v);});Widget _field(TextEditingController c,String label,{bool number=false,int maxLines=1,String? Function(String?)? validator})=>Padding(padding:const EdgeInsets.only(bottom:12),child:TextFormField(controller:c,keyboardType:number?TextInputType.number:TextInputType.text,maxLines:maxLines,decoration:InputDecoration(labelText:label),validator:validator));String? _req(String? v)=>v==null||v.trim().isEmpty?(AppLocalizations.of(context)?.requiredField??'Required'):null;String? _port(String? v){final t=v?.trim()??'';if(t.isEmpty)return null;final p=int.tryParse(t);return p==null||p<1||p>65535?(AppLocalizations.of(context)?.invalidPort??'Invalid port'):null;}}
