import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../l10n/app_localizations.dart';
import '../models/system_info.dart';
import '../providers/session_provider.dart';

class SystemInfoScreen extends StatefulWidget{const SystemInfoScreen({super.key});@override State<SystemInfoScreen> createState()=>_SystemInfoScreenState();}
class _SystemInfoScreenState extends State<SystemInfoScreen>{SystemInfo? _info;Object? _error;bool _loading=false;bool _rebooting=false;@override void didChangeDependencies(){super.didChangeDependencies();if(_info==null&&!_loading)_load(showSpinner:true);}Future<void> _load({bool showSpinner=false})async{final s=context.read<PfSenseSessionProvider>();if(!s.connected||s.service==null){setState(()=>_error=AppLocalizations.of(context)?.disconnectedMessage);return;}if(showSpinner)setState(()=>_loading=true);try{final i=await s.service!.getSystemInfo();if(mounted)setState((){_info=i;_error=null;});}catch(e){if(mounted){setState(()=>_error=e);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}}finally{if(mounted&&showSpinner)setState(()=>_loading=false);}}Future<bool?> _confirm(String m){final l=AppLocalizations.of(context);return showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:Text(l?.confirm??'Confirm'),content:Text(m),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:Text(l?.cancel??'Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:Text(l?.confirm??'Confirm'))]));}Future<void> _reboot()async{final l=AppLocalizations.of(context);if(await _confirm(l?.rebootConfirm??'Reboot this pfSense system?')!=true)return;if(await _confirm(l?.rebootFinalConfirm??'Confirm reboot')!=true)return;setState(()=>_rebooting=true);try{await context.read<PfSenseSessionProvider>().service!.rebootSystem();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}finally{if(mounted)setState(()=>_rebooting=false);}}
@override Widget build(BuildContext context){final l=AppLocalizations.of(context);final s=context.watch<PfSenseSessionProvider>();final i=_info;return RefreshIndicator(onRefresh:()=>_load(showSpinner:true),child:ListView(padding:const EdgeInsets.all(16),children:[if(!s.connected)_msg(Icons.cloud_off_outlined,l?.disconnectedMessage??'Disconnected')else if(_loading)const Padding(padding:EdgeInsets.all(32),child:Center(child:CircularProgressIndicator()))else if(_error!=null)_msg(Icons.error_outline,_error.toString())else if(i==null)_msg(Icons.info_outline,l?.emptyState??'Nothing to show yet.')else ...[_card(l?.version??'Version',i.version,Icons.new_releases_outlined),_card(l?.platform??'Platform',i.platform,Icons.router_outlined),_card(l?.architecture??'Architecture',i.architecture,Icons.developer_board_outlined),_card(l?.phpVersion??'PHP version',i.phpVersion,Icons.code),_card(l?.kernelVersion??'Kernel version',i.kernelVersion,Icons.terminal),_card(l?.repositoryType??'Repository type',i.repositoryType,Icons.inventory_2_outlined),const SizedBox(height:20),FilledButton.icon(onPressed:_rebooting?null:_reboot,icon:const Icon(Icons.power_settings_new),label:Text(l?.reboot??'Reboot'))]]));}Widget _card(String a,String b,IconData i)=>Card(child:ListTile(leading:Icon(i),title:Text(a),subtitle:Text(b,maxLines:2,overflow:TextOverflow.ellipsis)));Widget _msg(IconData i,String t)=>Card(child:ListTile(leading:Icon(i),title:Text(t)));}
